_wandb:
    value:
        cli_version: 0.28.0
        e:
            feq13orlnk5x2h7lkr1ozzcdumvdduyg:
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "134865870848"
                        used: "865988608"
                email: atlindell@gmail.com
                executable: /global/cfs/cdirs/m4474/alindell/cwola-summer/.venv/bin/python
                git:
                    commit: 352c9101e098050398c869783c909240468dec4b
                    remote: git@github.com:alindell0/cwola-summer.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-6a31ae28-d25a-2967-4da5-5770e3bd48ef
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-d04b5f3a-30b4-90ee-c589-3d2297df7f5c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-65d77aaa-da1b-18d3-4cd9-abb2819e42d5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-268fb93c-59d7-9e50-82ef-44221652fc02
                host: nid001453
                memory:
                    total: "269731745792"
                os: Linux-6.4.0-150600.23.103_15.0.25-cray_shasta_c-x86_64-with-glibc2.38
                program: <python with no main file>
                python: CPython 3.13.11
                root: /global/cfs/cdirs/m4474/alindell/cwola-summer/simulated-streams
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "128"
                    cpus_per_task: "128"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: m4474_g
                    job_cpus_per_node: "128"
                    job_end_time: "1784674859"
                    job_gid: "114425"
                    job_gpus: 0,1,2,3
                    job_id: "56271280"
                    job_licenses: u2:1
                    job_name: jupyter
                    job_nodelist: nid001453
                    job_num_nodes: "1"
                    job_partition: urgent_gpu_ss11
                    job_qos: gpu_jupyter
                    job_start_time: "1784653259"
                    job_uid: "114425"
                    job_user: alindell
                    jobid: "56271280"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001453
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001453
                    submit_dir: /global/u2/a/alindell
                    submit_host: login03
                    task_pid: "394964"
                    tasks_per_node: "1"
                    topology_addr: global.group8.nid001453
                    topology_addr_pattern: switch.switch.node
                    tres_bind: gres/gpu:per_task:4
                    tres_per_task: cpu=128,gres/gpu=4
                startedAt: "2026-07-21T17:13:44.345175Z"
                writerId: feq13orlnk5x2h7lkr1ozzcdumvdduyg
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.11
            "5": 0.28.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.28.0
            "13": linux-x86_64
test_fold:
    value: 0
train_loop:
    value: 0
val_set:
    value: 1
